# Defaults for all prettier-supported languages.
# Prettier will complete this with settings from .editorconfig file.
bracketSpacing: false
printWidth: 88
proseWrap: always
semi: true
trailingComma: "es5"
xmlWhitespaceSensitivity: "ignore"
tabWidth: 4

overrides:
    - files:
          - "hr_holidays_webform/views/report.xml"
          - "hr_holidays_webform/data/leave_report_mail_template.xml"
          - "hr_holidays_webform/data/leave_requests_mail_template.xml"
      options:
          printWidth: 240
    - files: "*.(yaml|yml)"
      options:
          tabWidth: 2
